### ISSUE TITLE
Tests (or traversal) seem not completely determenistic

### ISSUE THREAD

**Issue by andreasbaumann** [fosskers/microlens-aeson#1]
Experienced on Archlinux32 (32-bit Intel):

```
runhaskell Setup test:

    : FAIL
      test/Test.hs:53:
      expected: [Number 4.0,Number 7.0]
       but got: [Number 7.0,Number 4.0]
    : FAIL
      test/Test.hs:54:
      expected: "{\"a\":40,\"b\":70}"
       but got: "{\"b\":70,\"a\":40}"
```

**Comment by fosskers** [comment]
Well that's interesting. Does the same thing happen with `lens-aeson`?

**Comment by fosskers** [comment]
I haven't seen this anywhere else, so I'm closing.

**Comment by deep-42-thought** [comment]
This issue still persist.
I'm currently unable to test this with `lens-aeson` as it seems, several dependencies for the testsuite are not packaged in archlinux (and archlinux32). What's the non-distribution way to compile a stack of haskell-packages? I.e. the way with the least key strokes to get all dependencies of the test suite running on some system?

**Comment by fosskers** [comment]
It would be:

1. Get `stack` installed somehow (perhaps via the [stack-static](https://aur.archlinux.org/packages/stack-static/) AUR package)
2. Clone this repository, or [lens-aeson](https://github.com/lens/lens-aeson/) if that's what you want to test
3. In the cloned directory, `stack test --fast`. For `lens-aeson`, you may have to do `stack init` first.

Generally it's deeply unrecommended to install Haskell libs on Arch via `pacman`, etc.

**Comment by andreasbaumann** [comment]
Tried stack-static from the AUR, it's 64-bit only,
https://github.com/fosskers/microlens-aeson.git

If I check https://github.com/commercialhaskell/stack/releases
I see a stack-1.9.3-linux-i386.tar.gz but no 
stack-1.9.3-linux-i386-static.tar.gz

The way to reproduce it on Archlinux is:

```
asp export haskell-microlens-aeson
cd haskell-microlens-aeson
makepkg -s
less src/microlens-aeson-2.3.0.1/dist/test/microlens-aeson-2.3.0.1-microlens-aeson-test.log
```

Doing this on Archlinux (64-bit Intel) results in all tests passing.
Doing this on Archlinux32 and ArchlinuxARM (armv7h) results in:

```
    : FAIL
      test/Test.hs:51:
      expected: [Number 4.0,Number 7.0]
       but got: [Number 7.0,Number 4.0]
    : FAIL
      test/Test.hs:52:
      expected: "{\"a\":40,\"b\":70}"
       but got: "{\"b\":70,\"a\":40}"
```
(ARM seems to be not really supported by LLVM, but I doubt this is the problem here).

This could be a Archlinux-specific problem, so, I tried on a Fedora 29 (32-bit):

```
dnf install ghc-aeson-devel ghc-tasty ghc-HUnit ghc-microlens-devel \
  ghc-tasty-devel ghc-tasty-hunit-devel
dnf install ghc-compiler
dnf install haskell-platform
tar zxvf microlens-aeson-2.3.0.1.tar.gz
cd microlens-aeson-2.3.0.1
echo -e "import Distribution.Simple\nmain = defaultMain" > Setup.hs
runhaskell Setup configure -O --enable-shared --enable-executable-dynamic --disable-library-vanilla --docdir=/usr/share/doc/haskell-microlens-aeson --enable-test --dynlibdir=/usr/lib
runhaskell Setup build
runhaskell Setup test
```

retults also in 

```
    : FAIL
      test/Test.hs:51:
      expected: [Number 4.0,Number 7.0]
       but got: [Number 7.0,Number 4.0]
    : FAIL
      test/Test.hs:52:
      expected: "{\"a\":40,\"b\":70}"
       but got: "{\"b\":70,\"a\":40}"
```

Usually this is an indication that hash keys are not deterministic between platforms,
so you have to sort the test data before comparing for equality. This could well be
also a problem in Haskell itself or in the unit testing framework.

**Comment by woffs** [comment]
I get this with NixOS on i686-linux.

**Comment by samplet** [comment]
I looked at this on GNU Guix and discovered two things.  First, there’s this relevant [Aeson issue](https://github.com/bos/aeson/issues/568).  Second, I can confirm that [lens-aeson](https://github.com/lens/lens-aeson/) has the same problem (at least at version 1.0.2).

**Comment by fosskers** [comment]
@samplet can you describe your system more fully? I'd like to find a way to be able to test this myself.

**Comment by samplet** [comment]
If you are interested in installing Guix (either as an operating system or as a package manager on a different GNU/Linux system), I can give you instructions on how to reproduce the issue from there.

I imagine this bug would show up anywhere you can run 32-bit code and get a 32-bit copy of GHC and Cabal.  I believe both Debian and Ubuntu would let you do this on x86_64 using multiarch (as they both have 32-bit versions of GHC and Cabal).  I mention this because it might be a more familiar option than Guix.
