### ISSUE TITLE
Add `IsKey`?

### ISSUE THREAD

**Issue by sjshuck** [fosskers/microlens-aeson#31]
Per https://github.com/lens/lens-aeson/pull/44.  `_Key` can't be an `Iso'` here, but a `Lens'`; I'm not sure which direction it should go, or even if it makes sense to port this here.

**Comment by sjshuck** [comment]
> I'm not sure which direction it should go

Sorry, this didn't make sense.  What I was thinking was, since `_Key` can only go one direction here (`Lens' Key s`) and there's no corresponding "unkey" optic offered upstream that goes the other way, I'm not sure any part of this can appear here without being hamstrung.

Let's not add it.  (The other two currently open PRs can be merged IMHO.)

**Comment by fosskers** [comment]
Thanks for all this work - I will get to it today or tomorrow.
