### ISSUE TITLE
GHC 9.8 still not supported

### ISSUE THREAD

**Issue by thomasjm** [fosskers/microlens-aeson#41]
Commit b34c8be seems to be mistaken, as the most recent Stackage resolver introduced there is `lts-22.8`, which corresponds to GHC 9.6.4 -- not 9.8.

Could you take a look at #40? That will add actual support for 9.8. I'd be happy to update the CI as well if you like. Thanks!

**Comment by fosskers** [comment]
Forgive me, no idea how I missed that PR. I've released an updated version, `2.5.2`. Can you confirm?

**Comment by thomasjm** [comment]
Works for me, thanks!
